# Generated by Django 3.0.4 on 2020-05-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientsReg',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('gender', models.CharField(default='None', max_length=50)),
                ('doc_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=20)),
                ('password1', models.CharField(help_text='Minimum of 8 Characters', max_length=30)),
                ('password2', models.CharField(help_text='Minimum of 8 Characters', max_length=30)),
            ],
        ),
    ]
