# Generated by Django 3.0.3 on 2020-04-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorregistration',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
