# Generated by Django 3.0.4 on 2020-04-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20200430_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorregistration',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
