# Generated by Django 3.0.3 on 2020-05-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20200501_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorregistration',
            name='id',
        ),
        migrations.AddField(
            model_name='doctorregistration',
            name='dept',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorregistration',
            name='doc_id',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorregistration',
            name='hospital',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
