# Generated by Django 3.0.4 on 2020-05-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_auto_20200501_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('AID', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(default='None', max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=20)),
                ('treatement', models.CharField(max_length=300)),
            ],
        ),
    ]
