# Generated by Django 3.0.4 on 2020-05-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregistration',
            name='gender',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
