# Generated by Django 3.0.4 on 2020-05-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='password1',
            field=models.CharField(help_text='Minimum of 8 Characters', max_length=30),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='password2',
            field=models.CharField(help_text='Minimum of 8 Characters', max_length=30),
        ),
    ]
